language: ruby
rvm:
  - 2.3.0
  - 2.2.4
bundler_args: --jobs=2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
    - master

before_install:
  - gem update --system

install:
  - gem install bundler --no-ri --no-rdoc
  - bundle install
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
